version: 0.0
os: linux
files:
  - source: ./gs-rest-service-cors-0.1.0.jar
    destination: /home
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_application
      timeout: 300
      