version: 0.0
os: linux
files:
  - source: /
    destination: /home
hooks:
  BeforeInstall:
    - location: ./dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./setup.sh
      timeout: 300
      runas: root
      