version: 0.2

phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - nginx.conf
    - target/test-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
    
    