version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y install mysql-server
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - testui/*
    - target/test-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
    
    