version: 0.2

phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/gs-rest-service-cors-0.1.0.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
    
    